ASYNC_PROC_TIME_SLEEP: 65      #Время ожидания после добавления данных в очередь FIFO. Меньше 65 не ставить
SMS_TIME_SLEEP: 30             #Время ожидания между SMS
gsm_password: CHECK         #Пароль для взаимодействия с GSM
gsm_url: CHECK    #URL для отправки SMS на GSM
headers: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
  Gecko) Chrome/70.0.3538.102 Safari/537.36
login: CHECK
password: CHECK
time_send:                     #Час и минута отправки SMS в tuple
- 7                            #Час
- 1                            #Минута
url: CHECK
telegram_token: CHECK

